### ISSUE TITLE
Fix the processing (signing) of table rows

### ISSUE THREAD

**Issue by tomtomcrypto** [telosnetwork/telos-oracle-scripts#10]
## Description

Right now rows are signed in one batch
Should be smaller batches and wait for previous batch to finish

## Tasks

- [x] Implement Promise pool with configurable batch size

## Acceptance

- [x] Rows are processed in small batches and wait for the previous one to finish
- [x] Oracles can configure the batch size
